### PR TITLE
Proto3 optional field

### PR DESCRIPTION
**Pull request by kevpie**
Enables Marshalling and Unmarshalling the more recent proto3 optional fields capability.

Not thoroughly tested, I hope to use this on some non trivial messages before a merge is even considered.

Looking for feedback and suggestions.

Addresses #13

### CODE REVIEW

**Comment by devesh25427** [comment]
Are we planning to merge this pull request?

**Comment by awltr** [comment]
Would be great if we could merge this pull request

**Comment by derekperkins** [comment]
This seems sufficient to me. The protojson package is doing the heavy lifting supporting optional, this really just needs to declare support

**Comment by derekperkins** [comment]
@mitchellh any hesitations about merging this?

**Comment by mitchellh** [comment]
This looks good thanks! Apologies for the delay. :)

**Comment by charnan** [comment]
@mitchellh Please create a new tag

**Comment by jalaziz** [comment]
Just ran into this problem while trying to use the Buf remote plugin. Unfortunately, Buf only releases updates for stable releases. Any chance this will be released soon?

**Pull request merged**
